apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-test-17
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/chatbot-test-17:ab0ee9ccbc3046b52ec53cdf6f3cd87fc8196bd1@sha256:68f68e2953800e519132107e749afaa25525b284e131e05e3919be16680ccdb5 # use pre-built to bootstrap
          name: app-inference
